import { TunnelType, type PinggyOptions } from "@pinggy/pinggy";
// @ts-ignore
export const TUNNEL_CONFIG: (PinggyOptions & { configId: string })[] = [
    {
        configId: "4ddea4c7-9c3a-4051-a3f1-04a60c55bc9a",
        token: "adsfadsf",
        serverAddress: "a.pinggy.io",
        forwarding: "localhost:8000",
        webDebugger: "",
        tunnelType: [TunnelType.Http],
        ipWhitelist: [],
        bearerTokenAuth: [],
        basicAuth: [],
        headerModification: [],
        xForwardedFor: "" as any,
        httpsOnly: false,
        originalRequestUrl: false,
        allowPreflight: false,
        reverseProxy: false,
        force: true,
    },
    {
        configId: "4ddea4c7-9c3a-4051-a3f1-04a60c55bc9b",
        token: "adsfadsf",
        serverAddress: "a.pinggy.io",
        forwarding: "localhost:8000",
        webDebugger: "",
        tunnelType: [TunnelType.Udp],
        ipWhitelist: [],
        bearerTokenAuth: [],
        basicAuth: [],
        headerModification: [],
        xForwardedFor: "" as any,
        httpsOnly: false,
        originalRequestUrl: false,
        allowPreflight: false,
        reverseProxy: false,
        force: true,
    },
];
