import { type PinggyOptions } from "@pinggy/pinggy";
// @ts-ignore
export const TUNNEL_CONFIG: (PinggyOptions & { configId: string })[] = [
    {
        configId: "4ddea4c7-9c3a-4051-a3f1-04a60c55bc9a",
        token: "adsfadsf",
        serverAddress: "a.pinggy.io",
        forwardTo: "localhost:8000",
        debug: true,
        debuggerPort: 0,
        type: "http" as "http",
        ipWhitelist: [],
        basicAuth: {},
        bearerAuth: [],
        headerModification: [],
        xff: "" as any,
        httpsOnly: false,
        fullRequestUrl: false,
        allowPreflight: false,
        noReverseProxy: false,
        force: true,
    },
    {
        configId: "4ddea4c7-9c3a-4051-a3f1-04a60c55bc9b",
        token: "adsfadsf",
        serverAddress: "a.pinggy.io",
        forwardTo: "localhost:8000",
        debug: true,
        debuggerPort: 0,
        type: "http" as "http",
        ipWhitelist: [],
        basicAuth: {},
        bearerAuth: [],
        headerModification: [],
        xff: "" as any,
        httpsOnly: false,
        fullRequestUrl: false,
        allowPreflight: false,
        noReverseProxy: false,
        force: true,
    },
];